on:
  release:
    types: [created]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
    outputs:
      short-commit: ${{steps.commit.outputs.short}}

  release:
    name: make release
    needs: get-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "kubectl-history"
        ldflags: "-X github.com/wd/kubectl-history/cmd.Version=${{github.ref_name}}-${{needs.get-tags.outputs.short-commit}}"

    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.39
