on:
  release:
    types: [created]

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
        with:
          commit: "${{ github.event.workflow_run.head_sha }}"
          prefix: "sha-"

  release:
    name: make release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [386, amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "kubectl-v"
        ldflags: "github.com/wd/kubectl-v/cmd.Version=${{env.RELEASE_TAG}}-${{steps.commit.outputs.short}}"
